### ISSUE TITLE
Join table two table

### ISSUE THREAD

**Issue by jimit-hothi** [asyafrudin/catalogue#4]
Hello,

I can join two table or more table using this ??

this also need lazyload,

so can you guide me how i can do this ???

**Comment by asyafrudin** [comment]
On joining two tables, of course you can. The views that is used to retrieve the list of products is basically joining the product and the category table. However, in this example, data manipulation simply points to the product table. So, if you need to update two tables at once, you need to modify the code.

On lazy load, I can't help you with that. I'm not familiar with the plugin. Sorry about that.
